### ISSUE TITLE
What about an offcial release now including binaries? :) (this is not an issue)

### ISSUE THREAD

**Issue by rwbc** [spinojara/bitbit#3]
Hi again Ellmer,

Sorry for asking here, but I think quite some people would be interested in your program.

CCRL also would test it, if an official release would follow now.

Even the buggy version, which could not play more than 49 moves (under windows) had good result
in the tournaments of Carlos Pagador. (whom I provided my compilation)

https://www.talkchess.com/viewtopic.php?t=83657

Guenther (RWBC)
https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM/edit#gid=175552346

**Comment by spinojara** [comment]
I was actually just now working on an official release. I just have to get some help from a friend to test a couple of windows related things. It will probably be out sometime tonight. I will update you here when it is out.

**Comment by spinojara** [comment]
Done. See https://github.com/Spinojara/bitbit/releases/tag/v1.1.

**Comment by rwbc** [comment]
Nice!
