### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by SzotsGabor** [spinojara/bitbit#4]
Hi Isak,

I guess 1.1 is not going to be the last version. And in that case I think it a good idea to put the versionnumber in the engine UCI id and in the file name as well.

Gabor Szots
CCRL testing group

**Comment by spinojara** [comment]
Sure. That marks bitbit 1.2 https://github.com/Spinojara/bitbit/releases/tag/v1.2. There is no elo difference compared to bitbit 1.1. No playing related features were changed.

**Comment by spinojara** [comment]
Also, may I ask to 1. get accepted into the ccrl forums with the same username as here. And 2. for you to change the name from BitBit to bitbit. The name is bitbit, no letters captitalized.

Thank you!

**Comment by SzotsGabor** [comment]
1. If you have applied to be accepted you will be accepted. I am not sure how long it takes because I am not a site administrator but I'll see to it.
2. I intended to use bitbit so no problem there. But it is not on the list yet so there is nothing to be changed anyway.
