### ISSUE TITLE
connection stalls in CuteChess

### ISSUE THREAD

**Issue by tissatussa** [spinojara/bitbit#5]
i compiled your v1.2 from a current `git clone` and i let the engine play a few games in CuteChess GUI .. it seems to run fine, but then this happened : 

![bitbit-v1 2-connection-stalls](https://github.com/Spinojara/bitbit/assets/1109281/4ef48b9b-3b1c-4763-8fe9-7459da395049)

when time's up, it's curious CuteChess ends the game after 24 seconds .. with such engine "behaviour" normally CuteChess ends the game after 15 seconds : maybe bitbit v1.2 was very 'busy' and didn't listen to the CuteChess stop command ?

here's the CuteChess log tail :

```
<Bitbit v1.2 NNUE(4): info depth 21 seldepth 30 score cp 2052 nodes 1790016 time 1467 nps 1220000 pv f2e1 d2g2 g4g5 g2g1 e1f2 g1g5 h6f7 h8g8 f7g5 h7h6 g5f3 g8f8 b7c7 c5c4 b3c4 f8e8 c7a7 a6a5 f3d4 e8f8 a7a5 f8g8 a5h5
<Bitbit v1.2 NNUE(4): info depth 22 seldepth 34 score cp 2340 nodes 3608175 time 3045 nps 1184669 pv f2e1 d2d4 b7b8 h8g7 h6f5 g7f6 f5d4 f6e5 d4e2 e5d5 b8a8 d5e6 a8a6 e6f7 a6h6 f7g7 h6c6 h7h6 e1d2 g7h7 c6c5 h7g6 e2d4 g6g7 d4f5
>Bitbit v1.2 NNUE(4): stop
>Topas v1.3.3(5): isready
<Topas v1.3.3(5): readyok
```

[ i'm on Xubuntu 22.04 ]

**Comment by spinojara** [comment]
That is correct. bitbit does not currently listen for the stop command. 

I'm working on it, but I do not know how I want to implement it yet. I assume pthreads is the way to go...

**Comment by tissatussa** [comment]
> I assume pthreads is the way to go...

good luck finding a solution for this!
you might consult other chess engine programmers for this ?

main thing is that bitbit v1.2 runs out of time .. this shouldn't happen .. i remember the author(s) of the 4KU engine apply a simple rule to calculate the max time to spend on a move, regarding the remaining time, you could ask them.

**Comment by spinojara** [comment]
If bitbit runs out of time there is something else happening. Can you send me the full logs?

**Comment by tissatussa** [comment]
> Can you send me the full logs?

No, they're gone, i closed the game. I sent you the log tail, that's most relevant - the full log wouldn't give more insight.

btw. regarding `pthreads` etc : i found https://github.com/tinycthread/tinycthread/tree/master .. it's a bit old. but it may help.

**Comment by spinojara** [comment]
That is unfortunate.

However keep in mind that the full log would indeed be very helpful. If I could see the previous commands sent by cutechess I would be able to see from which position bitbit searched when the hang occured.

The most useful part of the log would be where cutechess sent "position startpos moves ..." and "go ...".

Thank you for the contribution.

**Comment by spinojara** [comment]
See 4ddbeca.

**Comment by tissatussa** [comment]
> ...the full log wouldn't give more insight

so i thought .. i can run a game again and see if the same happens but it's probably rare.

implementing "Add stop and ponder" is a good idea : `stop` is needed by basic UCI, `ponder` is nice.

**Comment by spinojara** [comment]
Yes, it's probably rare so there is no point in trying to recreate it. But if you ever happen to encounter the bug again the future please open a new issue. Thank you for the help!

**Comment by tissatussa** [comment]
> That is correct. bitbit does not currently listen for the stop command.
> I'm working on it, but I do not know how I want to implement it yet. I assume pthreads is the way to go...

what about pthreads ? do you want to implement it ?

**Comment by spinojara** [comment]
Yes, it is already done. See 4ddbeca.

**Comment by tissatussa** [comment]
[sorry for proceding this Issue while you closed it, i can open any new Issue - do you mind ? ]

**Comment by tissatussa** [comment]
it's hard to conclude your newest code is good when no more `connection stalls` happens .. anyhow i will keep using bitbit for my test games and report.

**Comment by spinojara** [comment]
Hmm, I got another idea. Is it possible that cutechess sends negative times to my engine or not?

**Comment by tissatussa** [comment]
see my recent (!) https://github.com/bdmendes/camel/issues/219 : yes, CuteChess may.

**Comment by tissatussa** [comment]
these days sometimes my Linux tends to freeze due to many open programs doing someting .. then the system clock (seconds, my main indicator) stops -for a while- i can then hardly move the mouse ..

i don't remember bitbit running then, CuteChess will adjust times after such freeze, i don't know what happens when the system is at its limits ..

**Comment by spinojara** [comment]
If your computer freezes it seems unfair to assume that it's bitbit fault for stalling. I have not experienced any such stalls with bitbit.
